config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }, controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: %i[index]

  resources :passed_tests, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/admin.rb
class Admin < User
  has_many :tests
end

app/models/answer.rb
class Answer < ApplicationRecord
  MAXIMUM_ANSWER = 4

  belongs_to :question

  validates :body, presence: true
  validate :answer_count

  scope :correct, -> { where correct: true }

  def answer_count
    errors.add(:base, 'У одного вопроса может быть от 1 до 4 ответов') if question && question.answers.size > MAXIMUM_ANSWER
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges
  has_many :users, through: :user_badges
  has_one :badge_rule
end

app/models/badge_rule.rb
class BadgeRule < ApplicationRecord
  belongs_to :badge
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests

  validates :title, presence: true

  default_scope { order(title: :asc) }
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user

  validates :message, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :url, presence: true
end

app/models/passed_test.rb
class PassedTest < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_update :before_update_set_next_question

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def successfully?
    self.correct_questions == self.test.questions.count
  end

  def check_result
    BadgeUserService.new(self).call if successfully?
  end

  def set_timer
    if timer_present?
      return unless test.timer

      timer = test.timer

      self.time_end = Time.zone.now + (timer * 60)
    end
  end

  def set_timer!
    set_timer
    save!
  end

  def timer_present?
    self.test.timer.present?
  end

  def time_is_up?
    (time_end - Time.zone.now).negative? if timer_present?
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_update_set_next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort if correct_answers
  end

  def correct_answers
    current_question&.answers&.correct
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers
  has_many :gists

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :admin
  has_many :questions
  has_many :passed_tests
  has_many :users, through: :passed_tests

  validates :title, presence: true
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :title, uniqueness: { scope: :level }

  scope :simple_tests, -> { where level: 0..1 }
  scope :middle_tests, -> { where level: 2..4 }
  scope :difficult_tests, -> { where level: 5..Float::INFINITY }
  scope :list_tests_by, ->(category_title) { joins(:category).where(categories: { title: category_title }).order(title: :desc).pluck(:title) }
  scope :levels_test, ->(level) { where(level: level) }
  scope :categories_test, ->(title) { joins(:category).where(categories: { title: title }) }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :trackable, :confirmable

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze

  before_save :before_save_formatting_email

  has_many :passed_tests
  has_many :tests, through: :passed_tests
  has_many :gists
  has_many :feedbacks
  has_many :user_badges
  has_many :badges, through: :user_badges

  validates :name, :email, presence: true
  validates :email, uniqueness: true, format: { with: VALID_EMAIL_REGEX }

  def passed_tests_by(level)
    Test.joins(:passed_tests).where(passed_tests: { user_id: id }, level: level).pluck(:title)
  end

  def passed_test(test)
    passed_tests.order(id: :desc).find_by(test_id: test.id)
  end

  private

  def before_save_formatting_email
    self.email = email.downcase
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end

  def author
  end
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: %i[show edit update destroy]

  def index
    @badges = Badge.all
  end

  def show; end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path, notice: 'Badge successfully created'
    else
      redirect_to :new
    end
  end

  def edit; end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path, notice: 'Badge successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def badge_params
    params.require(:badge).permit(:title, :img_url)
  end

  def set_badge
    @badge = Badge.find(params[:id])
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :authenticate_user!

  def index
    @badges = Badge.all
    @user_badges = current_user.badges
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to 'TestGuru', "https://github.com/#{author}/#{repo}", target: '_blank', rel: 'noopener'
  end

  def bootstrap_class_for_flash(flash_type)
    case flash_type
    when 'success'
      'alert-success'
    when 'error'
      'alert-danger'
    when 'alert'
      'alert-warning'
    when 'notice'
      'alert-info'
    else
      flash_type.to_s
    end
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/passed_tests_helper.rb
module PassedTestsHelper
  SUCCESS_RATE = 85

  def result_message
    percentage_success = @passed_test.correct_questions * 100 / @passed_test.test.questions.count
    if percentage_success >= SUCCESS_RATE
      content_tag(:p, "You have successfully passed the test, the percentage of success - #{percentage_success}%", style: 'color: green')
    else
      content_tag(:p, "Test failed, the percentage of success - #{percentage_success}%", style: 'color: red')
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header
    if @question.new_record?
      "Create New #{@test.title} Question"
    else
      "Edit #{@question.test.title} Question"
    end
  end
end

app/helpers/tests_helper.rb
module TestsHelper
  def format_timer(test)
    unless test.timer.nil?
      if test.timer <= 60
        format('00:' '%02d', (test.timer / 60).to_s)
      else
        test.timer * 60
        format('%02d', (test.timer / 60).to_s) + format(':' '%02d', (test.timer % 60).to_s)
      end
    end
  end
end

app/views/admin/badges/_badge.html.erb
<tr>  
    <td><%=  badge.title %></td>
    <td><img src="<%=  badge.img_url.html_safe %>"></td>
    <td><%= link_to 'Show', admin_badge_path(badge) %></td>
    <td><%= link_to 'Edit', edit_admin_badge_path(badge) %></td>
    <td><%= link_to 'Delete', admin_badge_path(badge), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/admin/badges/_form.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-12">
    <%= form_with model: [:admin, @badge], local: true do |form| %>
      <%= render 'shared/errors', resource: @badge%>

      <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
      </p>

      <p>
        <%= form.label :img_url %><br>
        <%= form.text_field :img_url %>
      </p>

      <p><%= form.submit %></p>
    <% end %>  

    <%= link_to 'Back', admin_badges_path %>
  </div>
</div>

app/views/admin/badges/edit.html.erb
<h4>Edit Badge</h4>

<%= render 'form' %>

app/views/admin/badges/index.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-12">
    <h2>All Badges</h2>

    <%= render 'shared/errors', resource: @badge %>
    <table class="table table-striped">
      <thead>
        <tr class="table-primary">
          <th>Title</th>
          <th>Image</th>
          <th colspan="3" class="text-center">Actions</th>
        </tr>  
      <%= render @badges %>
    </table>
    <%= link_to 'New Badge', new_admin_badge_path %>
  </div>  
</div>

app/views/admin/badges/new.html.erb
<h4>Create Badge</h4>

<%= render 'form' %>

app/views/admin/badges/show.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-12">
    <%= @badge.title %>  
    <hr>  

    <p> 
      <img src="<%= @badge.img_url %>">
    </p>

    <%= link_to 'Back', admin_badges_path %>
  </div>
</div>

app/views/badges/_badge.html.erb
<tr>  
    <td><%= badge.title %></td>
    <td><img src="<%=  badge.img_url.html_safe %>"></td>
</tr>

app/views/badges/_user_badge.html.erb
<tr>  
    <td><%= user_badge.title %></td>
    <td><img src="<%=  user_badge.img_url.html_safe %>"></td>
</tr>

app/views/badges/index.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-12">
    <h2>All badges</h2>
    <table class="table table-striped">
      <thead>
        <tr class="table-primary">
          <th>Title</th>
          <th>Image</th>
        </tr>  
      <%= render @badges %>
    </table>
    
    <h2>Your badges</h2>
    <table class="table table-striped">
      <thead>
        <tr class="table-primary">
          <th>Title</th>
          <th>Image</th>
        </tr>  
      <%= render @user_badges %>
    </table>
    
    <p><%= link_to 'Back', tests_path %></p>
  </div>  
</div>