config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }, controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: %i[index]

  resources :passed_tests, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/admin.rb
class Admin < User
  has_many :tests
end

app/models/answer.rb
class Answer < ApplicationRecord
  MAXIMUM_ANSWER = 4

  belongs_to :question

  validates :body, presence: true
  validate :answer_count

  scope :correct, -> { where correct: true }

  def answer_count
    errors.add(:base, 'У одного вопроса может быть от 1 до 4 ответов') if question && question.answers.size > MAXIMUM_ANSWER
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges
  has_many :users, through: :user_badges
  has_one :badge_rule
end

app/models/badge_rule.rb
class BadgeRule < ApplicationRecord
  belongs_to :badge
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests

  validates :title, presence: true

  default_scope { order(title: :asc) }
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user

  validates :message, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :url, presence: true
end

app/models/passed_test.rb
class PassedTest < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_update :before_update_set_next_question

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def successfully?
    self.correct_questions == self.test.questions.count
  end

  def check_result
    BadgeUserService.new(self).call if successfully?
  end

  def set_timer
    if timer_present?
      return unless test.timer

      timer = test.timer

      self.time_end = Time.zone.now + (timer * 60)
    end
  end

  def set_timer!
    set_timer
    save!
  end

  def timer_present?
    self.test.timer.present?
  end

  def time_is_up?
    (time_end - Time.zone.now).negative? if timer_present?
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_update_set_next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort if correct_answers
  end

  def correct_answers
    current_question&.answers&.correct
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers
  has_many :gists

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :admin
  has_many :questions
  has_many :passed_tests
  has_many :users, through: :passed_tests

  validates :title, presence: true
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :title, uniqueness: { scope: :level }

  scope :simple_tests, -> { where level: 0..1 }
  scope :middle_tests, -> { where level: 2..4 }
  scope :difficult_tests, -> { where level: 5..Float::INFINITY }
  scope :list_tests_by, ->(category_title) { joins(:category).where(categories: { title: category_title }).order(title: :desc).pluck(:title) }
  scope :levels_test, ->(level) { where(level: level) }
  scope :categories_test, ->(title) { joins(:category).where(categories: { title: title }) }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :trackable, :confirmable

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze

  before_save :before_save_formatting_email

  has_many :passed_tests
  has_many :tests, through: :passed_tests
  has_many :gists
  has_many :feedbacks
  has_many :user_badges
  has_many :badges, through: :user_badges

  validates :name, :email, presence: true
  validates :email, uniqueness: true, format: { with: VALID_EMAIL_REGEX }

  def passed_tests_by(level)
    Test.joins(:passed_tests).where(passed_tests: { user_id: id }, level: level).pluck(:title)
  end

  def passed_test(test)
    passed_tests.order(id: :desc).find_by(test_id: test.id)
  end

  private

  def before_save_formatting_email
    self.email = email.downcase
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to 'TestGuru', "https://github.com/#{author}/#{repo}", target: '_blank', rel: 'noopener'
  end

  def bootstrap_class_for_flash(flash_type)
    case flash_type
    when 'success'
      'alert-success'
    when 'error'
      'alert-danger'
    when 'alert'
      'alert-warning'
    when 'notice'
      'alert-info'
    else
      flash_type.to_s
    end
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header
    if @question.new_record?
      "Create New #{@test.title} Question"
    else
      "Edit #{@question.test.title} Question"
    end
  end
end

app/helpers/tests_helper.rb
module TestsHelper
  def format_timer(test)
    unless test.timer.nil?
      if test.timer <= 60
        format('00:' '%02d', (test.timer / 60).to_s)
      else
        test.timer * 60
        format('%02d', (test.timer / 60).to_s) + format(':' '%02d', (test.timer % 60).to_s)
      end
    end
  end
end

app/views/admin/_navigation.html.erb
<nav class="navbar navbar-light bg-light mb-3">
  <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
  <%= link_to 'Admin panel', admin_tests_path %>
  <span class="navbar-text">
    Welcome, <b class="nav-admin user-name"><%= current_user.name %></b> Admin |
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
  </span>
</nav>

app/views/layouts/_footer.html.erb
<hr>
<footer class="footer">
  <small>
    <%= t('.current_year', year: current_year) %> |
    <%= t('.author') %> |
    Project - <%= github_url("sergeynakul", "TestGuru") %> |
    <%= t('.description') %> |
    <%= link_to t('.thinknetica_link'), "http://thinknetica.com/", target: "_blank" %>
  </small>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-light bg-light mb-3">
  <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
  <%= link_to 'Admin panel', admin_tests_path if current_user.is_a?(Admin) %>
  <span class="navbar-text">
    <% if user_signed_in? %>
      <%= t('.welcome', name: current_user.name) %> |
      <%= link_to t('.exit'), destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to t('.signup'), new_user_registration_path %> |
      <%= link_to t('.login'), new_user_session_path %>
    <% end %>
  </span>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin panel | TestGuru</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'admin/navigation' %>
    <div class="container">
      <%= render partial: 'shared/flash', flash: flash %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>TestGuru</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render partial: 'shared/flash', flash: flash %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: "resource-errors", data: { resource_id: resource.id } do %>
    <h3><%= t('.header', count: resource.errors.count) %>:</h3>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<div class="container">
  <% flash.each do |type, msg| %>
    <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show">
      <%= msg %>
      <button class="close" data-dismiss="alert">x</button>
    </div>
  <% end %> 
</div>